######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 15 08:27:32 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h PaintArea.h
SOURCES += main.cpp MainWindow.cpp PaintArea.cpp
